CSupportWebApp/Models/ErrorViewModel.cs
using System;

namespace CSupportWebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CSupportWebApp/Models/TicketVM.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CSupportWebApp.Models
{
    public class TicketVM : IValidatableObject
    {

        public TicketVM(string title, string body, DateTime dueTime)
        { 
            Title = title;
            Body = body;
            DueTime = dueTime;
        }

        public TicketVM() { }

        [Required]
        [MinLength(1)]
        [MaxLength(64)]
        public string Title { get; set; }
        [MinLength(1)]
        [MaxLength(1024)]
        public string Body { get; set; }
        [Required]
        public DateTime DueTime { get; set;}

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (DueTime.ToUniversalTime() < DateTime.UtcNow)
            {
                yield return new ValidationResult(
                
                    "Can't add overdue ticket.", 
                    new [] {"DueTime"});
            }
        }
    }
}

CSupportWebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CSupportWebApp.Models;

namespace CSupportWebApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CSupportWebApp/Controllers/TicketsController.cs
using System;
using System.Threading.Tasks;
using CSupportWebApp.Commands;
using CSupportWebApp.Models;
using CSupportWebApp.Queries;
using MediatR;
using Microsoft.AspNetCore.Mvc;

namespace CSupportWebApp.Controllers
{
    public class TicketsController : Controller
    {
        //private readonly ITicketCommandService _commands;
        //private readonly ITicketQueryService _queries;
        private readonly IMediator _mediator;

        public TicketsController(IMediator mediator)
        {
            _mediator = mediator;
        }

        // GET: Tickets
        public async Task<IActionResult> Index()
        {
            return View(await _mediator.Send(new GetVisibleTicketsQuery()));

            // return View(await _mediator.Send(new GetVisibleTicketsQuery { OnlyCritical = true }));
        }


        // GET: Tickets/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Tickets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([FromForm] TicketVM ticketVM)
        {
            if (ModelState.IsValid)
            {
                await _mediator.Send(new CreateTicketCommand
                {
                    Title = ticketVM.Title,
                    Body = ticketVM.Body,
                    DueTime = ticketVM.DueTime
                });
                return RedirectToAction(nameof(Index));
            }
            return View(ticketVM);
        }

        public async Task<IActionResult> CloseTicket(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            try
            {
                await _mediator.Send(new CloseTicketCommand { Id = (int)id });
            }
            catch (InvalidOperationException)
            {
                return NotFound();
            }
            
            return RedirectToAction(nameof(Index));
        }
    }
}

CSupportWebApp/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

CSupportWebApp/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CSupportWebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

CSupportWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Customer Support Tickets system</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/custom.css" type="text/css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/jquery-ui.css" />
        <link rel="stylesheet" href="~/css/jquery-ui.structure.css" />
        <link rel="stylesheet" href="~/css/jquery.datetimepicker.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/jquery-ui.css" />
        <link rel="stylesheet" href="~/css/jquery-ui.structure.css" />
        <link rel="stylesheet" href="~/css/jquery.datetimepicker.css" />
    </environment>

    @RenderSection("Styles", false)
</head>
<body>
    <nav class="custom navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a asp-area="" asp-controller="Tickets" asp-action="Index" class="custom navbar-brand">CS Ticket system</a>
            </div>
        </div>
    </nav>

    <div class="custom container body-content">
        @RenderBody()
    </div>

    <footer class="fixed-bottom">
        <div class="row">
            <div class="col-md-6 col-sm-6">
                <h5>Lorem ipsum</h5>
                <h6>Dolor sit amet</h6>
                <h6>Consectetur adipiscing elit</h6>
                <h6>Sed do eiusmod</h6>
                <h6>Tempor incididunt</h6>
            </div>
            <div class="col-md-6 col-sm-6">
                <h5>Kontakt</h5>
                <p class="footer-p">Tallinn</p>
                <p class="footer-p">Akadeemia Tee 7/2 216A</p>
                <p class="footer-p">+372 56937010</p>
            </div>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/lib/jquery.datetimepicker.full.js"></script>
        <script src="~/lib/jquery-ui.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="https://github.com/xdan/datetimepicker/blob/master/build/jquery.datetimepicker.full.js"
                asp-fallback-src="~/lib/jquery.datetimepicker.full.js"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-ui.js"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

CSupportWebApp/Views/Tickets/Create.cshtml
@model TicketVM

@{
    ViewData["Title"] = "Create";
}

<h1>Create a new support ticket</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" autocomplete="off"/>
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Body" class="control-label">Description</label>
                <input asp-for="Body" class="form-control" autocomplete="off"/>
                <span asp-validation-for="Body" class="text-danger"></span>
            </div>
            <div class="form-group input-group date">
                <label asp-for="DueTime" class="control-label">Deadline</label>
                <input asp-for="DueTime" class="form-control datetimepicker" autocomplete="off" type="text"/>
                <span asp-validation-for="DueTime" class="text-danger">
                </span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
    <script>
        var setMinTime = function(currentDateTime) {
            if (currentDateTime.getDate == today) {
                this.setOptions({
                    minTime: 0
                });
            } else {
                this.setOptions({
                    minTime: false
                });
            }
        };
        $(".datetimepicker").datetimepicker({
            format: 'm.d.Y H:i',
            lang: 'et',
            minDate: 0
        });
    </script>
   
}

CSupportWebApp/Views/Tickets/Delete.cshtml
@model DTO.SupportTicketBLLDTO
@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SupportTicket</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Body)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Body)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TimeCreated)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TimeCreated)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DueTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DueTime)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CSupportWebApp/Views/Tickets/Details.cshtml
@model Domain.SupportTicket

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>SupportTicket</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Body)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Body)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TimeCreated)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TimeCreated)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DueTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DueTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsVisible)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsVisible)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CSupportWebApp/Views/Tickets/Edit.cshtml
@model DTO.SupportTicketBLLDTO

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>SupportTicket</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Body" class="control-label"></label>
                <input asp-for="Body" class="form-control" />
                <span asp-validation-for="Body" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TimeCreated" class="control-label"></label>
                <input asp-for="TimeCreated" class="form-control" />
                <span asp-validation-for="TimeCreated" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DueTime" class="control-label"></label>
                <input asp-for="DueTime" class="form-control" />
                <span asp-validation-for="DueTime" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CSupportWebApp/Views/Tickets/Index.cshtml
@model IEnumerable<Domain.SupportTicket>

@{
    ViewData["Title"] = "Tickets";
}

<h1>Active tickets</h1>

<div class="row">
    <div class="index-list">
        <table class="index-list-table">
            <thead>
                <tr class="">
                    <th class="col-md-2 text-center">
                        Title
                    </th>
                    <th class="col-md-5 text-center">
                        Description
                    </th>
                    <th class="col-md-2 text-center">
                        Time opened
                    </th>
                    <th class="col-md-2 text-center">
                        Deadline
                    </th>
                    <th  class=" col-md-1 text-center">
                        Close
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    // Critical colour formatting logic
                    var remainingTime = item.DueTime.Subtract(DateTime.UtcNow);
                    var criticalStyle = remainingTime.TotalMinutes < 60 ? "color:Red" : null;

                    // Formatted time strings
                    var timeCreated = item.TimeCreated.ToLocalTime().ToString("HH:mm dd.MM.yy");
                    var dueTime = item.DueTime.ToLocalTime().ToString("HH:mm dd.MM.yy");
                    <tr>
                        <td class="col-md-2 index-list-item" style="@criticalStyle">
                            @Html.DisplayFor(modelItem => item.Title)
                        </td>
                        <td class="col-md-5 index-list-item" style="@criticalStyle">
                            @Html.DisplayFor(modelItem => item.Body)
                        </td>
                        <td class="col-md-2 index-list-item">
                            @Html.DisplayFor(modelItem => timeCreated)
                        </td>
                        <td class="col-md-2 index-list-item" style="@criticalStyle">
                            @Html.DisplayFor(modelItem => dueTime)
                        </td>

                        <td class=" col-md-1 text-center">
                            <a asp-action="CloseTicket" asp-route-id="@item.Id">
                                <img src="~/images/checkmark.png" />
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<p>
    <a asp-action="Create">Create New</a>
</p>